### ISSUE TITLE
mac os10.13上面运行start.command提示symbol binding failed: Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by chenr0129** [trojan-gfw/trojan#352]
chendeiMac:trojan chen$ ./trojan
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chen/Desktop/trojan/./trojan (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chen/Desktop/trojan/./trojan (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
chendeiMac:trojan chen$

**Comment by KunagisaYuki** [comment]
@chenr0129 Update your OS.

**Comment by petsgre** [comment]
is there any solution avoid to update mac OS？

**Comment by GreaterFire** [comment]
@petsgre Hold on. Looking into this. What's the version you are running?

**Comment by petsgre** [comment]
@GreaterFire macos mojave 10.13 and trojan 1.15

**Comment by GreaterFire** [comment]
@chenr0129 @petsgre See if this works. If it works, I'll replace the release version with this file.
[trojan-1.15.0-macos.zip](https://github.com/trojan-gfw/trojan/files/4371375/trojan-1.15.0-macos.zip)

**Comment by petsgre** [comment]
@GreaterFire I upgraded my mac to 10.13 Higt Sierra ,and used trojan 1.14.0,it works fine now.
And i tested trojan that you provided with current mac version,trojan runed,but can't connnect with internet

**Comment by GreaterFire** [comment]
@petsgre Please provide some logs or I can't help you.

**Comment by XieJiSS** [comment]
@GreaterFire No, this was not fixed by the version 1.15.1.

The new binary you attached before resulted in this:

```
$ ./trojan
Welcome to trojan 1.15.0
[2020-03-30 14:43:51] [WARN] trojan service (client) started at 127.0.0.1:1080
[2020-03-30 14:43:54] [INFO] 127.0.0.1:51515 requested connection to github.com:443
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/trojan/./trojan
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/trojan/./trojan
  Expected in: /usr/lib/libSystem.B.dylib

zsh: abort      ./trojan
```

which is the same error message as that of release 1.15.1.

There's no hardship starting either version's binary, but as soon as I try to *actually* use it to access the Internet, it breaks and triggers Apple's error reporting process.

According to [this link](https://github.com/Homebrew/homebrew-core/pull/46983#issuecomment-556906673) and [this link](https://github.com/Homebrew/homebrew-core/pull/46983#issuecomment-557703973), this might be caused by a too-high Xcode version (>= 11) specified on the CI.

**Comment by GreaterFire** [comment]
I can't help with it since Azure Pipelines recently removed macOS 10.13. Instead, try installing through brew: `brew install trojan-gfw/trojan/trojan`.

**Comment by XieJiSS** [comment]
OK, thanks anyway

And it would be nice if this could be mentioned as a note for macOS 10.13 users ;-)

**Comment by Wnine16** [comment]
I had the same problem on OS X El Capitan (10.11.6), it worked fine before as the version (1.14.1). Since I update to 1.15.0, I got this error. (the same as 1.15.1).

我在10.11.6这个版本的mac中也遇到了这个问题，之前一直都正常的，版本(<=1.14.1)都是可以用的，自从1.15.0 (包括1.15.1) 开始，就会有同样的提示错误了。

**Comment by GreaterFire** [comment]
Please don't report this issue anymore - it won't be fixed. Install trojan via `brew` instead.

**Comment by cc978** [comment]
从 brew 上安装 trojan 的确没这个bug了，看情况是从源码编译的，如下。
不过 trojan 14 和 15 服务端和客户端貌似不兼容，还是要保留多个版本。
```
==> Installing trojan from trojan-gfw/trojan
==> Downloading https://github.com/trojan-gfw/trojan/archive/v1.15.1.tar.gz
==> Downloading from https://codeload.github.com/trojan-gfw/trojan/tar.gz/v1.15.
######################################################################## 100.0%
==> sed -i  s/server\.json/client.json/ CMakeLists.txt
==> cmake . -DENABLE_MYSQL=OFF
==> make install
==> Caveats
```

**Comment by GreaterFire** [comment]
They are compatible
