### ISSUE TITLE
Compilation failed after upgrading boost to 1.66.0-1

### ISSUE THREAD

**Issue by GreaterFire** [trojan-gfw/trojan#21]
```
$ cmake .. && make
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   atomic
--   chrono
--   date_time
--   system
--   thread
-- Found OpenSSL: /usr/lib/libcrypto.so (found suitable version "1.1.0g", minimum required is "1.0.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/src/troj/trojan/build
Scanning dependencies of target trojan
[  9%] Building CXX object CMakeFiles/trojan.dir/src/clientsession.cpp.o
In file included from /home/user/src/troj/trojan/src/clientsession.h:23:0,
                 from /home/user/src/troj/trojan/src/clientsession.cpp:20:
/home/user/src/troj/trojan/src/session.h:43:74: error: 'stream_socket_service' is not a member of 'boost::asio'
     virtual boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket() = 0;
                                                                          ^~~~~~~~~~~~~~~~~~~~~
/home/user/src/troj/trojan/src/session.h:43:74: note: suggested alternative: 'make_service'
     virtual boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket() = 0;
                                                                          ^~~~~~~~~~~~~~~~~~~~~
                                                                          make_service
/home/user/src/troj/trojan/src/session.h:43:74: error: 'stream_socket_service' is not a member of 'boost::asio'
/home/user/src/troj/trojan/src/session.h:43:74: note: suggested alternative: 'make_service'
     virtual boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket() = 0;
                                                                          ^~~~~~~~~~~~~~~~~~~~~
                                                                          make_service
/home/user/src/troj/trojan/src/session.h:43:116: error: wrong number of template arguments (2, should be 1)
 t::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket() = 0;
                                                                          ^
In file included from /usr/include/boost/asio/basic_datagram_socket.hpp:20:0,
                 from /usr/include/boost/asio.hpp:23,
                 from /home/user/src/troj/trojan/src/session.h:26,
                 from /home/user/src/troj/trojan/src/clientsession.h:23,
                 from /home/user/src/troj/trojan/src/clientsession.cpp:20:
/usr/include/boost/asio/basic_socket.hpp:60:7: note: provided for 'template<class Protocol> class boost::asio::basic_socket'
 class basic_socket
       ^~~~~~~~~~~~
In file included from /home/user/src/troj/trojan/src/clientsession.h:23:0,
                 from /home/user/src/troj/trojan/src/clientsession.cpp:20:
/home/user/src/troj/trojan/src/session.h:43:118: error: expected unqualified-id before '>' token
 :asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket() = 0;
                                                                          ^
In file included from /home/user/src/troj/trojan/src/clientsession.cpp:20:0:
/home/user/src/troj/trojan/src/clientsession.h:53:66: error: 'stream_socket_service' is not a member of 'boost::asio'
     boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket();
                                                                  ^~~~~~~~~~~~~~~~~~~~~
/home/user/src/troj/trojan/src/clientsession.h:53:66: note: suggested alternative:
make_service'
     boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket();
                                                                  ^~~~~~~~~~~~~~~~~~~~~
                                                                  make_service
/home/user/src/troj/trojan/src/clientsession.h:53:66: error: 'stream_socket_service' is not a member of 'boost::asio'
/home/user/src/troj/trojan/src/clientsession.h:53:66: note: suggested alternative:
make_service'
     boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket();
                                                                  ^~~~~~~~~~~~~~~~~~~~~
                                                                  make_service
/home/user/src/troj/trojan/src/clientsession.h:53:108: error: wrong number of template arguments (2, should be 1)
 t::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket();
                                                                          ^
In file included from /usr/include/boost/asio/basic_datagram_socket.hpp:20:0,
                 from /usr/include/boost/asio.hpp:23,
                 from /home/user/src/troj/trojan/src/session.h:26,
                 from /home/user/src/troj/trojan/src/clientsession.h:23,
                 from /home/user/src/troj/trojan/src/clientsession.cpp:20:
/usr/include/boost/asio/basic_socket.hpp:60:7: note: provided for 'template<class Protocol> class boost::asio::basic_socket'
 class basic_socket
       ^~~~~~~~~~~~
In file included from /home/user/src/troj/trojan/src/clientsession.cpp:20:0:
/home/user/src/troj/trojan/src/clientsession.h:53:110: error: expected unqualified-id before '>' token
 :asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >& accept_socket();
                                                                          ^
/home/user/src/troj/trojan/src/clientsession.cpp:39:45: error: 'stream_socket_service' is not a member of 'boost::asio'
 boost::asio::basic_socket<tcp, boost::asio::stream_socket_service<tcp> >& ClientSession::accept_socket() {
                                             ^~~~~~~~~~~~~~~~~~~~~
/home/user/src/troj/trojan/src/clientsession.cpp:39:45: note: suggested alternative: 'make_service'
 boost::asio::basic_socket<tcp, boost::asio::stream_socket_service<tcp> >& ClientSession::accept_socket() {
                                             ^~~~~~~~~~~~~~~~~~~~~
                                             make_service
/home/user/src/troj/trojan/src/clientsession.cpp:39:45: error: 'stream_socket_service' is not a member of 'boost::asio'
/home/user/src/troj/trojan/src/clientsession.cpp:39:45: note: suggested alternative: 'make_service'
 boost::asio::basic_socket<tcp, boost::asio::stream_socket_service<tcp> >& ClientSession::accept_socket() {
                                             ^~~~~~~~~~~~~~~~~~~~~
                                             make_service
/home/user/src/troj/trojan/src/clientsession.cpp:39:70: error: wrong number of template arguments (2, should be 1)
 boost::asio::basic_socket<tcp, boost::asio::stream_socket_service<tcp> >& ClientSession::accept_socket() {
                                                                      ^
In file included from /usr/include/boost/asio/basic_datagram_socket.hpp:20:0,
                 from /usr/include/boost/asio.hpp:23,
                 from /home/user/src/troj/trojan/src/session.h:26,
                 from /home/user/src/troj/trojan/src/clientsession.h:23,
                 from /home/user/src/troj/trojan/src/clientsession.cpp:20:
/usr/include/boost/asio/basic_socket.hpp:60:7: note: provided for 'template<class Protocol> class boost::asio::basic_socket'
 class basic_socket
       ^~~~~~~~~~~~
/home/user/src/troj/trojan/src/clientsession.cpp:39:72: error: expected unqualified-id before '>' token
 boost::asio::basic_socket<tcp, boost::asio::stream_socket_service<tcp> >& ClientSession::accept_socket() {
                                                                        ^
make[2]: *** [CMakeFiles/trojan.dir/build.make:63: CMakeFiles/trojan.dir/src/clientsession.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/trojan.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by klzgrad** [comment]
BOOST_ASIO_ENABLE_OLD_SERVICES

> The service template parameters, and the corresponding classes, are disabled by default. For example, instead of basic_socket<Protocol, SocketService> we now have simply basic_socket<Protocol>. The old interface can be enabled by defining the BOOST_ASIO_ENABLE_OLD_SERVICES macro.

**Comment by GreaterFire** [comment]
Thanks. I will fix it ASAP.
